version: '3'
services:
  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - znuny-708_default

  worker:
    build:
      context: .
    hostname: worker
    command: celery -A main worker --loglevel=info
    depends_on:
      - redis
    networks:
      - znuny-708_default

  api:
    build:
      context: .
    hostname: api
    command: python api.py
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - znuny-708_default

  flower:
    build: ./flower/
    hostname: flower
    command: celery -A tasks flower
    volumes:
      - ./flower/examples:/data
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - api
      - worker
      - redis
    networks:
      - znuny-708_default   

networks:
  znuny-708_default:
    external: true      